### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by cferdinandi** [enkidevs/smooth-scroll#1]
Hi guys... totally cool to say no, but... is there *any* chance I could convince you to hand over the `smooth-scroll` namespace on NPM? A bunch of people have asked me to host [my plugin](https://cferdinandi.github.io/smooth-scroll) there. It's under active development, well documented and maintained, etc.

You're obviously totally within your rights to keep it, but I'd be insanely appreciative if you let me use it for my project.

Thanks in advance!

**Comment by mathieudutour** [comment]
Happy to transfer the namespace.

I’ll need a bit of time to publish under a new namespace and make the changes in our codebase so our builds don’t break as the API are completely different (jQuery-style vs programmatic style) and we actively use our lib.

Could I ask you to thank https://enki.com and https://github.com/enkidevs for the namespace in your release notes? 😄

**Comment by cferdinandi** [comment]
Happy to! Closing this issue and moving the discussion over to email. Thanks @mathieudutour!
